name: Build Runner Image

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Toolchain environment to build
        default: stable
      version:
        type: string
        required: true
        description: Version tag to use on this release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cargo-leptos-runner-${{ inputs.environment }}

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ekshore/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ inputs.version }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}


      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            TOOLCHAIN=${{ inputs.environment }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.lables }}
          platforms: liunx/arm64,linux/amd64
